apiVersion: v1
kind: Service
metadata:
  name: {{ include "mirofish.api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mirofish.componentLabels" (dict "ctx" . "component" "api") | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.commonAnnotations) .Values.api.service.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "mirofish.componentSelectorLabels" (dict "ctx" . "component" "api") | nindent 4 }}
